<?php /** @var $block \Blackbird\TicketBlaster\Block\EventList */ ?>
<h1><?php echo __('Event list') ?></h1>
<ul class="ticketblaster-events-list">
    <?php /** @var $event \Blackbird\TicketBlaster\Model\Event */ ?>
    <?php foreach ($block->getEvents() as $event): ?>
        <li class="ticketblaster-event-list-item">
            <h3 class="ticketblaster-event-item-title">
                <a href="<?php echo $event->getUrl() ?>"><?php echo $event->getTitle() ?></a>
            </h3>
            <div class="ticketblaster-event-item-content"><?php echo $event->getContent(); ?></div>
            <div class="ticketblaster-event-item-meta">
                <strong><?php echo __('Event time:') ?></strong>
                <?php echo $event->getEventTime() ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>
